language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    - RUSTDOC_VERSION=nightly
    - secure: rZOyqGD8ZoqsOHt+diH4PbjddmEADVcTI3JgYebItyk7ArpTGrRU3cBzkB6N9gG86WDYVBqXUBdO0cGK/5iwtXJYdI4tWKVY8Y78TFFkhgthHk+8qs1qrm/r/gWM0UXoBybDvs7uGr/HzIKmguOCEBo9yBH/DY6evabqOEzwwtO++dMJ2vR4V555nzLW+RfPNak73Vvvx1jzfRE9/t6f0UfhsLItSH46FEN+vLnud/hl+gdYBsCQ3CpQSQTX2Izh4JN+70afXF+ya98vYuc8mlfAuP/fNmvbmcd640gOWYk2JDpccPLMYK6aGmQPI/ecpCd1jr8SoKGJUFSlpBuOqHiGoiJFF6iEXlHGAEKwwVlAs5VL5PYtYqtHVQK2UR4Ro2FR8rj8ldenoBYj2qQ6KtI9IqkrxUfJvEq+Tmfc8O20f3gpDDt9dvLni1qqJOWwMW3mPmx/5EAHotlEB+UoLV328AfpXYZY8TkTu8dHVzHz4ZYY/jndD0yTiBx4/KejQC4DnDIm52jWe66JL8WffYZTL9KLer0tkoaAXnUiKV+XFxFvexH94gDy6vABZvtyMaTfGYNLv/3AsKfHFGiPU+umTPtjNQYNuJiCYU0pRnnCIWIFZdkTCjJsQSeTQdVJYBDotg8HXyqAu+7ZGZeKYh/xiC7vvpwCNvjN+1+CFE8=

notifications:
  email: false
