[package]
name = "complex"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/complex"
homepage = "https://github.com/stainless-steel/complex"
description = "The package provides complex numbers."
