[package]
name = "complex"
version = "0.8.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/hilbert-space/complex"
homepage = "https://github.com/hilbert-space/complex"
description = "The package is deprecated in favor of num."
